#pragma once
#include "vgl.h"
#include "LoadShaders.h"
#include <iostream>
#include "vmath.h"
#include "assimp/Importer.hpp"
#include "assimp/scene.h"
#include "assimp/postprocess.h"
#include <glm-0.9.8.0/glm/glm.hpp>
#include <glm-0.9.8.0/glm/gtc/matrix_transform.hpp>
#include <glm-0.9.8.0/glm/gtc/type_ptr.hpp>
#include <stdio.h>
#include <vector>
#include <map>
#include<SOIL2/SOIL2.h>
#include <string>
#include <fstream>
#include <vector>
#include <sstream>
#include <iostream>
#include <windows.h>
